#!/bin/bash
#Create dir for files
mkdir $HOME/vpn && cd "$_"
#download SSTP from Sourceforge
wget -O sstp-client.tar.gz https://deac-ams.dl.sourceforge.net/project/sstp-client/sstp-client/sstp-client-1.0.16.tar.gz
#Unzip file
tar –xvzf sstp-client.tar.gz
#Install some other stuff
sudo apt-get update
sudo apt-get install ppp-dev
sudo apt-get install libevent-dev
sudo apt-get install libssl-dev
sudo apt-get update
#Make files, it's not funny...
cd sstp_client-1.0.16
./configure && make && make install


