#!/bin/bash
#Create dir for files
mkdir $HOME/vpn/ && cd "$_"
#download SSTP from Sourceforge
wget -O $HOME/vpn/sstp-client.tar.gz https://deac-ams.dl.sourceforge.net/project/sstp-client/sstp-client/sstp-client-1.0.16.tar.gz
tar -xvzf $HOME/vpn/sstp-client.tar.gz
#Install some other stuff
sudo apt-get update
sudo apt-get install ppp-dev
sudo apt-get install libevent-dev
sudo apt-get install libevent
sudo apt-get install libssl-dev
sudo apt-get update
sudo apt full-upgrade
#Make files, it's not funny...
cd $HOME/vpn/sstp-client-1.0.16
./configure --prefix=/usr && make && sudo make install


